### ISSUE TITLE
adding hints before a solution

### ISSUE THREAD

**Issue by HurayraIIT** [TanvirArjel/DataStructureAndAlgorithm#1]
Please add some hints before a solution to a particular problem. Taking hints and thinking about the problem more before rushing to the solution is ideal for problem solvers. Sometimes the problem might be related to a topic unknown to the solver. In that case, telling him which topic to learn or focus on is also helpful.

- Hints can be separated into levels such as **basic**, **strong** or **deep**.
- Helpful topics needed to learn before attempting a problem can also be added as **Prerequisite**

Thanks.

**Comment by TanvirArjel** [comment]
@HurayraIIT Thank you so much for your great suggestion. Surely I shall keep your suggestion in mind whenever any problem and its solution is added to the repository.
